version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    build: ./backend
    command: ["/app/entrypoint.sh"]
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
      - DJANGO_SUPERUSER_PASSWORD=Tamatem123@
      - DJANGO_SUPERUSER_USERNAME=root
      - DJANGO_SUPERUSER_EMAIL=root@example.com
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - VITE_BACKEND_URL=http://localhost:8000

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
